//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.DbModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class klassen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klassen()
        {
            this.schuelers = new HashSet<schueler>();
            this.stundens = new HashSet<stunden>();
        }
    
        public string K_ID { get; set; }
        public string K_Bez { get; set; }
        public Nullable<short> K_S_Klaspr { get; set; }
        public Nullable<short> K_S_Klasprstv { get; set; }
        public string K_L_Klavst { get; set; }
    
        public virtual lehrer lehrer { get; set; }
        public virtual schueler schueler { get; set; }
        public virtual schueler schueler1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<schueler> schuelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stunden> stundens { get; set; }
    }
}
