//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pruefungen
    {
        public System.DateTime P_Datum { get; set; }
        public short P_S_Kandidat { get; set; }
        public string P_L_Pruefer { get; set; }
        public string P_G_Fach { get; set; }
        public string P_Art { get; set; }
        public Nullable<byte> P_Note { get; set; }
    
        public virtual gegenstaende gegenstaende { get; set; }
        public virtual lehrer lehrer { get; set; }
        public virtual schueler schueler { get; set; }
    }
}
