//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.WpfDb1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Schule2000Entities : DbContext
    {
        public Schule2000Entities()
            : base("name=Schule2000Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gegenstaende> gegenstaendes { get; set; }
        public virtual DbSet<klassen> klassens { get; set; }
        public virtual DbSet<lehrer> lehrers { get; set; }
        public virtual DbSet<pruefungen> pruefungens { get; set; }
        public virtual DbSet<raeume> raeumes { get; set; }
        public virtual DbSet<schueler> schuelers { get; set; }
        public virtual DbSet<stunden> stundens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vorgesetzte> vorgesetztes { get; set; }
    }
}
