//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.DbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int CustomerIdt8 { get; set; }
        public string FirstNameo7 { get; set; }
        public string LastNameq2 { get; set; }
        public string Companyj9 { get; set; }
        public string Addressv5 { get; set; }
        public string Cityj6 { get; set; }
        public string Statem6 { get; set; }
        public string Countryo8 { get; set; }
        public string PostalCodew6 { get; set; }
        public string Phonex6 { get; set; }
        public string Faxp8 { get; set; }
        public string Emaila2 { get; set; }
        public Nullable<int> SupportRepIdf7 { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
