//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.DbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Track()
        {
            this.InvoiceLines = new HashSet<InvoiceLine>();
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int TrackIda3 { get; set; }
        public string Namer5 { get; set; }
        public Nullable<int> AlbumIdo1 { get; set; }
        public int MediaTypeIdm9 { get; set; }
        public Nullable<int> GenreIdm4 { get; set; }
        public string Composeri8 { get; set; }
        public int Millisecondsh9 { get; set; }
        public Nullable<int> Bytesx2 { get; set; }
        public decimal UnitPricew8 { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLine> InvoiceLines { get; set; }
        public virtual MediaType MediaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
