//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.Bestellungens = new HashSet<Bestellungen>();
            this.Personal1 = new HashSet<Personal>();
        }
    
        public int Personal_Nrr3 { get; set; }
        public string Nachnamel1 { get; set; }
        public string Vornamea1 { get; set; }
        public string Positionh2 { get; set; }
        public string Anredek9 { get; set; }
        public Nullable<System.DateTime> Geburtsdatumx5 { get; set; }
        public Nullable<System.DateTime> Einstellunga4 { get; set; }
        public string Straßeg5 { get; set; }
        public string Orte6 { get; set; }
        public string Regiono9 { get; set; }
        public string PLZl2 { get; set; }
        public string Landc3 { get; set; }
        public string TelefonPrivatg3 { get; set; }
        public string DurchwahlBueroj7 { get; set; }
        public byte[] Fotop5 { get; set; }
        public string Bemerkungenf4 { get; set; }
        public Nullable<int> Vorgesetzterd6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellungen> Bestellungens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personal> Personal1 { get; set; }
        public virtual Personal Personal2 { get; set; }
    }
}
