//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.Kundenbestellungen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelldetail
    {
        public int Bestell_Nrn8 { get; set; }
        public int Artikel_Nrk8 { get; set; }
        public decimal Einzelpreisw2 { get; set; }
        public short Anzahlt2 { get; set; }
        public float Rabattm4 { get; set; }
    
        public virtual Artikel Artikel { get; set; }
        public virtual Bestellungen Bestellungen { get; set; }
    }
}
