//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.Lieferanten
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kunden()
        {
            this.Bestellungens = new HashSet<Bestellungen>();
        }
    
        public string Kunden_Codeq1 { get; set; }
        public string Firmal3 { get; set; }
        public string Kontaktpersonb8 { get; set; }
        public string Positionk9 { get; set; }
        public string Straßel8 { get; set; }
        public string Orts6 { get; set; }
        public string Regionx8 { get; set; }
        public string PLZy8 { get; set; }
        public string Landp1 { get; set; }
        public string Telefonn1 { get; set; }
        public string Telefaxw9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellungen> Bestellungens { get; set; }
    }
}
