//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.Kundenbestellungen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieferanten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lieferanten()
        {
            this.Artikels = new HashSet<Artikel>();
        }
    
        public int Lieferanten_Nrf6 { get; set; }
        public string Firmak4 { get; set; }
        public string Kontaktpersonk7 { get; set; }
        public string Positionv2 { get; set; }
        public string Straßei6 { get; set; }
        public string Orti2 { get; set; }
        public string Regionc1 { get; set; }
        public string PLZe5 { get; set; }
        public string Landu4 { get; set; }
        public string Telefonk5 { get; set; }
        public string Telefaxd4 { get; set; }
        public string Homepagef6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artikel> Artikels { get; set; }
    }
}
