//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.Kundenbestellungen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategorien()
        {
            this.Artikels = new HashSet<Artikel>();
        }
    
        public int Kategorie_Nrk7 { get; set; }
        public string Kategorienamel7 { get; set; }
        public string Beschreibungj3 { get; set; }
        public byte[] Abbildungk1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artikel> Artikels { get; set; }
    }
}
