//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spengergasse.Lieferanten
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versandfirman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Versandfirman()
        {
            this.Bestellungens = new HashSet<Bestellungen>();
        }
    
        public int Firmen_Nri1 { get; set; }
        public string Firmae2 { get; set; }
        public string Telefonn9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestellungen> Bestellungens { get; set; }
    }
}
